{% set version = "0.0.9" %}

package:
  name: curated-tokenizers
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/curated-tokenizers/curated-tokenizers-{{ version }}.tar.gz
  sha256: c93d47e54ab3528a6db2796eeb4bdce5d44e8226c671e42c2f23522ab1d0ce25
  patches:
    - patches/0001-use-our-own-sentencepiece-abseil.patch

build:
  script: python -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - python
    - pip
    - setuptools
    - cython
    - libprotobuf
    - libsentencepiece
  run:
    - python
    - regex

test:
  requires:
    - pip
  imports:
    - curated_tokenizers
  commands:
    - pip check

about:
  home: https://github.com/explosion/curated-transformers
  summary: 'Lightweight piece tokenization library'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/explosion/curated-tokenizers

extra:
  recipe-maintainers:
    - h-vetinari
    - conda-forge/spacy
