{% set version = "2.0.0" %}

package:
  name: curated-tokenizers
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/curated-tokenizers/curated_tokenizers-{{ version }}.tar.gz
  sha256: 0a8f8c527bc93a6404ec0ba8f0df215b8c205edc81a05617fbbe705438804094
  patches:
    - patches/0001-use-our-own-sentencepiece-abseil.patch

build:
  script: python -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - python
    - pip
    - setuptools
    - cython
    - libprotobuf
    - libsentencepiece
  run:
    - python
    - regex

test:
  requires:
    - pip
  imports:
    - curated_tokenizers
  commands:
    - pip check

about:
  home: https://github.com/explosion/curated-transformers
  summary: 'Lightweight piece tokenization library'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/explosion/curated-tokenizers

extra:
  recipe-maintainers:
    - h-vetinari
    - conda-forge/spacy
